InformasiPertandingan/urls.py
from django.urls import path
from InformasiPertandingan.views import edit_match_flutter, delete_match_flutter, show_json_country, show_main, add_match, create_match_flutter, proxy_image, show_json, show_json_by_id, edit_match, delete_match, show_match, show_xml, show_xml_by_id
app_name = 'InformasiPertandingan'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-match/', add_match, name='add_match'),
    path('json/', show_json, name='show_json'),
    path('json/<str:match_id>/', show_json_by_id, name='show_json_by_id'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<str:match_id>/', show_xml_by_id, name='show_xml_by_id'),
    path('edit-match/<uuid:match_id>/', edit_match, name='edit_match'),
    path('edit-flutter/<str:match_id>/', edit_match_flutter, name='edit_match_flutter'),
    path('match/<uuid:id>/delete', delete_match, name='delete_match'),
    path('match/<str:id>/', show_match, name='show_match'),
    path('proxy-image/', proxy_image, name='proxy_image'),
    path('create-flutter/', create_match_flutter, name='create_match_flutter'),
    path('json-country/', show_json_country, name='show_json_country'),
    path('match/<str:id>/delete-flutter/', delete_match_flutter, name='delete_match_flutter')
]

forumApp/urls.py
from django.urls import path
from forumApp.views import show_landing_page, show_json, show_json_by_id, create_forum, get_comments, create_comment, show_thread_detail, edit_thread, delete_thread, edit_comment, delete_comment, increment_views, create_forum_flutter
app_name = 'forumApp'

urlpatterns = [
    path('', show_landing_page, name='show_landing_page'),
    path('json/', show_json, name="show_json"),
    path('json/<str:id>/', show_json_by_id, name="show_json_by_id"),    
    path('create/', create_forum, name='create_forum'),
    path('create_flutter/', create_forum_flutter, name='create_forum_flutter'),
    
    path('<str:thread_id>/comments/', get_comments, name='get_comments'),
    path('<str:thread_id>/comments/create/', create_comment, name='create_comment'),
    path('comment/edit/<str:comment_id>/', edit_comment, name='edit_comment'),
    path('comment/delete/<str:comment_id>/', delete_comment, name='delete_comment'),
    
    path('edit/<str:thread_id>/', edit_thread, name='edit_thread'),
    path('delete/<str:thread_id>/', delete_thread, name='delete_thread'),
    path('<str:thread_id>/', show_thread_detail, name='show_thread_detail'),  
    path('views/increment/<str:thread_id>/', increment_views, name='increment_views'),  
]

main/urls.py
from django.urls import path
from main.views import login_user, register, guest_login

app_name = 'main'

urlpatterns = [
    path('', login_user, name='login'),
    path('register/', register, name='register'),
    path('guest-login/', guest_login, name='guest_login'),
]

merchandiseApp/urls.py
from django.urls import path
from .views import show_main_merchandise, show_merchandise, create_merchandise_ajax, edit_merchandise_ajax, delete_merchandise_ajax, get_merchandise_json, show_xml, show_json, show_json_by_id, show_xml_by_id, increment_views

app_name = 'merchandiseApp'

urlpatterns = [
    path('', show_main_merchandise, name='show_main'),
    path('<uuid:id>/', show_merchandise, name='show_merchandise'),
    path('create/', create_merchandise_ajax, name='create_merchandise_ajax'),
    path('edit/<uuid:id>/', edit_merchandise_ajax, name='edit_merchandise_ajax'),
    path('delete/<uuid:id>/', delete_merchandise_ajax, name='delete_merchandise_ajax'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<uuid:merchandise_id>/', show_json_by_id, name='show_json_by_id'),
    path('xml/<uuid:merchandise_id>/', show_xml_by_id, name='show_xml_by_id'),
    path('get-merchandise/', get_merchandise_json, name='get_merchandise_json'),
    path('views/increment/<uuid:id>/', increment_views, name='increment_views'),
]

trophythreads/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('informasi/', include('InformasiPertandingan.urls')),
    path('merchandise/', include('merchandiseApp.urls')),
    path('forum/', include('forumApp.urls')),
    path('favorites/', include('favoritesApp.urls')),
    path('review/', include('reviewproduct.urls')),
    path('cart/', include('cartApp.urls')),
    path('auth/', include('authentication.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&family=Open+Sans:wght@300..800&display=swap"
        rel="stylesheet">

    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/dompurify@3.0.5/dist/purify.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}" />
</head>

<body>
    {% block content %} {% endblock content %}
    {% include 'toast.html' %}
</body>

</html>

templates/footer.html
{% load static %}
<footer class="bg-[var(--color-primary)] text-white">
  
  <div class="container mx-auto flex flex-col items-center gap-y-6 lg:flex-row lg:justify-between lg:items-center px-12 py-6">

    <!--Logo (Bagian Kiri)-->
    <div class="flex-shrink-0">
      <img src="{% static 'image/logo.png' %}" alt="Logo" class="h-14">
    </div>

    <!--Data Pembuat-->
    <div class="flex flex-col">
      <p class="text-sm font-bold text-white mb-2 text-center lg:text-right">Created by:</p>
      <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">

        <div class="text-center lg:text-right">
          <p class="font-semibold text-sm truncate">Amelia Juliawati</p>
          <p class="text-xs text-gray-200 truncate">2406414076</p>
        </div>

        <div class="text-center lg:text-right">
          <p class="font-semibold text-sm truncate">Giselle Julia R.</p>
          <p class="text-xs text-gray-200 truncate">2406415116</p>
        </div>

        <div class="text-center lg:text-right">
          <p class="font-semibold text-sm truncate">Gusti Niera F. A.</p>
          <p class="text-xs text-gray-200 truncate">2406496403</p>
        </div>

        <div class="text-center lg:text-right">
          <p class="font-semibold text-sm truncate">Febriyanti</p>
          <p class="text-xs text-gray-200 truncate">2406496214</p>
        </div>

        <div class="text-center lg:text-right">
          <p class="font-semibold text-sm truncate">Samuel M. T.</p>
          <p class="text-xs text-gray-200 truncate">2406435830</p>
        </div>

        <div class="text-center lg:text-right">
          <p class="font-semibold text-sm truncate">Elsa Mayora S.</p>
          <p class="text-xs text-gray-200 truncate">2406353250</p>
        </div>

      </div>
    </div>
  </div>
</footer>

templates/header.html
{% load static %}
<nav class="fixed top-0 left-0 w-full bg-[var(--color-primary)] shadow-sm border-b border-gray-200 z-50">
    <div class="mx-auto px-4 sm:px-12">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center space-x-10">
                <div class="flex items-center space-x-2">
                    <img src="{% static 'image/logo.png' %}" alt="TrophyThreads Logo" class="h-8">
                    <span class="px-2 text-white text-xl font-extrabold tracking-tight"
                        style="font-family: var(--font-title);">TrophyThreads</span>
                </div>

                <div style="font-family: var(--font-title);"
                    class="absolute left-1/2 transform -translate-x-1/2 hidden md:flex justify-evenly w-1/2">
                    <a href="{% url 'InformasiPertandingan:show_main' %}" class="text-white font-semibold hover:text-white transition duration-200">
                        Match
                    </a>
                    <a href="{% url 'merchandiseApp:show_main' %}" class="text-white font-semibold hover:text-white transition duration-200">
                        Merchandise
                    </a>
                    <a href="{% url 'forumApp:show_landing_page' %}" class="text-white font-semibold hover:text-white transition duration-200">
                        Discussion
                    </a>
                </div>
            </div>

            <div class="hidden md:flex items-center space-x-4">
                <div class="text-right">
                    <div class="text-sm font-semibold text-white leading-tight"> {{ user.username|default:"Guest" }}
                    </div>
                    <div class="text-xs text-gray-200 tracking-tight"> {{ user.profile.role|default:"No Role" }}</div>
                </div>
                <div class="relative">
                    <button id="profileButton" class="focus:outline-none">
                        <img src="{% static 'icons/profile-icon.png' %}" alt="Profile"
                            class="h-9 w-9 rounded-full cursor-pointer">
                    </button>

                    <div id="profileDropdown"
                        class="absolute right-0 mt-2 w-32 bg-white text-gray-800 rounded-lg shadow-lg hidden">
                        <a href="{% url 'main:login' %}" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 rounded-b-lg">
                            Logout
                        </a>
                    </div>
                </div>
            </div>

            <!-- Mobile Menu Button -->
            <div class="md:hidden flex items-center">
                <button class="mobile-menu-button p-2 text-white hover:text-white transition duration-200">
                    <span class="sr-only">Open menu</span>
                    <div class="w-6 h-6 flex flex-col justify-center items-center">
                        <span class="bg-white block h-0.5 w-6 rounded-sm mb-1"></span>
                        <span class="bg-white block h-0.5 w-6 rounded-sm mb-1"></span>
                        <span class="bg-white block h-0.5 w-6 rounded-sm"></span>
                    </div>
                </button>
            </div>
        </div>
    </div>

    <!-- === Mobile Menu === -->
    <div class="mobile-menu hidden md:hidden bg-[var(--color-primary)] text-white">
        <div class="px-4 py-4 space-y-4">
            <a href="{% url 'InformasiPertandingan:show_main' %}" class="block hover:text-white transition duration-200">
                Match
            </a>
            <a href="{% url 'merchandiseApp:show_main' %}" class="block hover:text-white transition duration-200">
                Merchandise
            </a>
            <a href="{% url 'forumApp:show_landing_page' %}" class="block hover:text-white transition duration-200">
                Discussion
            </a>

            <div class="border-t border-gray-300 pt-4">
                <a href="{% url 'main:login' %}" class="block text-bold text-white">Logout</a>
            </div>
        </div>
    </div>

    <script>
        const btn = document.querySelector("button.mobile-menu-button");
        const menu = document.querySelector(".mobile-menu");
        btn.addEventListener("click", () => {
            menu.classList.toggle("hidden");
        });

        const profileButton = document.getElementById("profileButton");
        const profileDropdown = document.getElementById("profileDropdown");

        profileButton.addEventListener("click", (e) => {
            e.stopPropagation();
            profileDropdown.classList.toggle("hidden");
        });

        document.addEventListener("click", (e) => {
            if (!profileDropdown.contains(e.target) && !profileButton.contains(e.target)) {
                profileDropdown.classList.add("hidden");
            }
        });
    </script>
</nav>

templates/toast.html
{% load static %}
<div id="toast-component"
    class="fixed top-4 left-1/2 transform -translate-x-1/2 p-2 px-6 translate-y-[-150%] opacity-0 bg-white shadow-xl rounded-t-xl rounded-b-none border border-gray-200 w-[90%] sm:w-[400px] md:w-[500px] p-4 flex items-center gap-3 transition-all duration-500 z-50">
    <span id="toast-icon" class="text-2xl"></span>
    <div class="flex-1">
        <p id="toast-message" class="text-gray-600 text-sm">This is a Sample Message</p>
    </div>
    <button id="toast-close" class="text-gray-400 hover:text-gray-700">&times;</button>

    <div id="toast-progress"
        class="absolute bottom-0 left-0 h-[4px] bg-blue-500 w-full scale-x-0 origin-left transition-transform duration-[4000ms]">
    </div>
</div>

<script src="{% static 'js/toast.js' %}"></script>